# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 23:24
from __future__ import unicode_literals

import assets_manager.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=32, null=True)),
                ('file', models.FileField(max_length=500, upload_to=assets_manager.models.upload_to_path)),
                ('filename', models.CharField(blank=True, max_length=128, null=True)),
                ('origin', models.CharField(choices=[('WEBUP', 'Web Upload'), ('FTP', 'FTP'), ('OTHER', 'Other')], default='WEBUP', max_length=20)),
                ('license', models.CharField(blank=True, choices=[('CC-BY', 'Createive Commons'), ('GPL', 'GPL'), ('BSD', 'BSD'), ('MIT', 'MIT'), ('C', 'Copyright')], default='C', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owned_at', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PRIVATE', 'Private'), ('INTERNAL', 'Internal'), ('PUBLIC', 'Public')], default='INTERNAL', max_length=20)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_owned', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
    ]
