# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='task_id',
            field=models.UUIDField(default=None, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
