# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0002_asset_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='task_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
