# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0003_auto_20170111_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256, unique=True, verbose_name='nome')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='bucket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_manager.AssetBucket'),
        ),
    ]
