# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0004_auto_20170119_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbucket',
            name='name',
            field=models.CharField(default='UNKNOW', max_length=256, unique=True, verbose_name='nome'),
        ),
    ]
