# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0005_auto_20170203_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='task_id',
            new_name='uuid',
        ),
    ]
