# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0006_auto_20170215_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='checksum',
            field=models.CharField(default='UNKNOW', max_length=32),
            preserve_default=False,
        ),
    ]
