# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0007_asset_checksum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='checksum',
            field=models.CharField(editable=False, max_length=32),
        ),
    ]
