# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_manager', '0008_auto_20170405_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='checksum',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
