# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_set_site_domain_and_name'),
        ('sites', '0003_auto_20160905_2010'),
    ]

    operations = [
    ]
